kind: Deployment
apiVersion: apps/v1
metadata:
  name: ilender-frontweb
  labels:
    app: ilender-application
    subname: frontweb
spec:
  selector:
    matchLabels:
      app: ilender-application
      subname: frontweb
  replicas: 1
  template:
    metadata:
      labels:
        app: ilender-application
        subname: frontweb
    spec:
      containers:
        - name: container-frontweb
          image: "gandigit/ilender-frontweb-ocp-logs:0.0.1"
          imagePullPolicy: Always
          ports:
            - name: my-http
              containerPort: 9070
              protocol: TCP
            - name: https
              containerPort: 8082
          envFrom:
            - configMapRef:
                name: ilender-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: ilender-frontweb
  labels:
    app: ilender-application
    subname: frontweb
spec:
  type: NodePort
  ports:
    - name: my-http
      port: 9090
      targetPort: my-http
      nodePort: 30501
  selector:
    app: ilender-application
    subname: frontweb
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ilender-frontweb
  labels:
    app: ilender-application
    subname: frontweb
spec:
  path: /
  to:
    kind: Service
    name: ilender-frontweb
    weight: 100
  port:
    targetPort: my-http
